USE csdlnc_keyspace;

INSERT INTO SinhVien (mssv, hoten, nganh, namsinh)
VALUES ('SV001', 'Nguyễn Văn A', 'Công nghệ thông tin', 2002);

INSERT INTO SinhVien (mssv, hoten, nganh, namsinh)
VALUES ('SV002', 'Trần Thị B', 'Kinh tế', 2001);

INSERT INTO SinhVien (mssv, hoten, nganh, namsinh)
VALUES ('SV003', 'Lê Văn C', 'Quản trị kinh doanh', 2003);

INSERT INTO SinhVien (mssv, hoten, nganh, namsinh)
VALUES ('SV004', 'Phạm Thị D', 'Kỹ thuật phần mềm', 2000);
